# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dna.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dna.proto',
  package='RemyBuffers',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tdna.proto\x12\x0bRemyBuffers\"0\n\x05Range\x12\x0b\n\x03low\x18= \x01(\x01\x12\x0c\n\x04high\x18> \x01(\x01\x12\x0c\n\x04incr\x18? \x01(\x01\"\xda\x02\n\x0b\x43onfigRange\x12/\n\x13link_packets_per_ms\x18G \x01(\x0b\x32\x12.RemyBuffers.Range\x12\x1f\n\x03rtt\x18H \x01(\x0b\x32\x12.RemyBuffers.Range\x12\'\n\x0bnum_senders\x18I \x01(\x0b\x32\x12.RemyBuffers.Range\x12\'\n\x0b\x62uffer_size\x18J \x01(\x0b\x32\x12.RemyBuffers.Range\x12-\n\x11mean_off_duration\x18K \x01(\x0b\x32\x12.RemyBuffers.Range\x12,\n\x10mean_on_duration\x18L \x01(\x0b\x32\x12.RemyBuffers.Range\x12\x18\n\x10simulation_ticks\x18M \x01(\r\x12\x30\n\x14stochastic_loss_rate\x18N \x01(\x0b\x32\x12.RemyBuffers.Range\"\xa9\x01\n\tNetConfig\x12\x18\n\x10mean_on_duration\x18\x01 \x01(\x01\x12\x19\n\x11mean_off_duration\x18\x02 \x01(\x01\x12\x13\n\x0bnum_senders\x18\x03 \x01(\r\x12\x10\n\x08link_ppt\x18\x04 \x01(\x01\x12\r\n\x05\x64\x65lay\x18\x05 \x01(\x01\x12\x13\n\x0b\x62uffer_size\x18\x06 \x01(\r\x12\x1c\n\x14stochastic_loss_rate\x18\x07 \x01(\x01\"6\n\x0c\x43onfigVector\x12&\n\x06\x63onfig\x18Q \x03(\x0b\x32\x16.RemyBuffers.NetConfig'
)




_RANGE = _descriptor.Descriptor(
  name='Range',
  full_name='RemyBuffers.Range',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='low', full_name='RemyBuffers.Range.low', index=0,
      number=61, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='RemyBuffers.Range.high', index=1,
      number=62, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='incr', full_name='RemyBuffers.Range.incr', index=2,
      number=63, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=74,
)


_CONFIGRANGE = _descriptor.Descriptor(
  name='ConfigRange',
  full_name='RemyBuffers.ConfigRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='link_packets_per_ms', full_name='RemyBuffers.ConfigRange.link_packets_per_ms', index=0,
      number=71, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rtt', full_name='RemyBuffers.ConfigRange.rtt', index=1,
      number=72, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_senders', full_name='RemyBuffers.ConfigRange.num_senders', index=2,
      number=73, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buffer_size', full_name='RemyBuffers.ConfigRange.buffer_size', index=3,
      number=74, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_off_duration', full_name='RemyBuffers.ConfigRange.mean_off_duration', index=4,
      number=75, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_on_duration', full_name='RemyBuffers.ConfigRange.mean_on_duration', index=5,
      number=76, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='simulation_ticks', full_name='RemyBuffers.ConfigRange.simulation_ticks', index=6,
      number=77, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stochastic_loss_rate', full_name='RemyBuffers.ConfigRange.stochastic_loss_rate', index=7,
      number=78, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=423,
)


_NETCONFIG = _descriptor.Descriptor(
  name='NetConfig',
  full_name='RemyBuffers.NetConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean_on_duration', full_name='RemyBuffers.NetConfig.mean_on_duration', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_off_duration', full_name='RemyBuffers.NetConfig.mean_off_duration', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_senders', full_name='RemyBuffers.NetConfig.num_senders', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='link_ppt', full_name='RemyBuffers.NetConfig.link_ppt', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delay', full_name='RemyBuffers.NetConfig.delay', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buffer_size', full_name='RemyBuffers.NetConfig.buffer_size', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stochastic_loss_rate', full_name='RemyBuffers.NetConfig.stochastic_loss_rate', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=595,
)


_CONFIGVECTOR = _descriptor.Descriptor(
  name='ConfigVector',
  full_name='RemyBuffers.ConfigVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='RemyBuffers.ConfigVector.config', index=0,
      number=81, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=651,
)

_CONFIGRANGE.fields_by_name['link_packets_per_ms'].message_type = _RANGE
_CONFIGRANGE.fields_by_name['rtt'].message_type = _RANGE
_CONFIGRANGE.fields_by_name['num_senders'].message_type = _RANGE
_CONFIGRANGE.fields_by_name['buffer_size'].message_type = _RANGE
_CONFIGRANGE.fields_by_name['mean_off_duration'].message_type = _RANGE
_CONFIGRANGE.fields_by_name['mean_on_duration'].message_type = _RANGE
_CONFIGRANGE.fields_by_name['stochastic_loss_rate'].message_type = _RANGE
_CONFIGVECTOR.fields_by_name['config'].message_type = _NETCONFIG
DESCRIPTOR.message_types_by_name['Range'] = _RANGE
DESCRIPTOR.message_types_by_name['ConfigRange'] = _CONFIGRANGE
DESCRIPTOR.message_types_by_name['NetConfig'] = _NETCONFIG
DESCRIPTOR.message_types_by_name['ConfigVector'] = _CONFIGVECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Range = _reflection.GeneratedProtocolMessageType('Range', (_message.Message,), {
  'DESCRIPTOR' : _RANGE,
  '__module__' : 'dna_pb2'
  # @@protoc_insertion_point(class_scope:RemyBuffers.Range)
  })
_sym_db.RegisterMessage(Range)

ConfigRange = _reflection.GeneratedProtocolMessageType('ConfigRange', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGRANGE,
  '__module__' : 'dna_pb2'
  # @@protoc_insertion_point(class_scope:RemyBuffers.ConfigRange)
  })
_sym_db.RegisterMessage(ConfigRange)

NetConfig = _reflection.GeneratedProtocolMessageType('NetConfig', (_message.Message,), {
  'DESCRIPTOR' : _NETCONFIG,
  '__module__' : 'dna_pb2'
  # @@protoc_insertion_point(class_scope:RemyBuffers.NetConfig)
  })
_sym_db.RegisterMessage(NetConfig)

ConfigVector = _reflection.GeneratedProtocolMessageType('ConfigVector', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGVECTOR,
  '__module__' : 'dna_pb2'
  # @@protoc_insertion_point(class_scope:RemyBuffers.ConfigVector)
  })
_sym_db.RegisterMessage(ConfigVector)


# @@protoc_insertion_point(module_scope)
